[[main]]
  name = "Projects"
  url = "/projects/"
  weight = 20

[[main]]
  name = "Publications"
  url = "/publications/"
  weight = 30

[[main]]
  name = "Now"
  url = "/now/"
  weight = 40

[[main]]
  name = "Thoughts"
  url = "/thoughts/"
  weight = 50

[[main]]
  name = "Contact"
  url = "/#contact"
  weight = 60

[[main]]
  name = "CV"
  url = "/files/cv-muchovej.pdf"
  weight = 100
