version: "3"

services:
  hugo:
    image: jojomi/hugo
    container_name: "john-muchovej-com"
    hostname: "john.muchovej.com"
    restart: unless-stopped
    environment:
      - HUGO_THEME=academic
      - HUGO_WATCH=1
      # - HUGO_DESTINATION=/output
      - HUGO_REFRESH_TIME=60
      # - HUGO_BASEURL=john.muchovej.com
    volumes:
      - .:/src
      # - ./output:/output
    ports: [ "1313:1313", ]
    command:
      - /run.sh
      - --disableFastRender
