version: "3.7"
services:
  hugo:
    image: jojomi/hugo:0.55.5
    environment:
      - HUGO_WATCH=true
      # - HUGO_BASEURL=ionlights.com
      # - HUGO_THEME=something
    container_name: "dev-hugo-ionlights-com"
    volumes:
      - .:/src
    ports:
      - 46669:1313
