version: "3"

services:
  hugo:
    image: jojomi/hugo:0.65.0
    container_name: "john-muchovej-com"
    hostname: "john.muchovej.com"
    restart: unless-stopped
    volumes:
      - .:/src
      # use the volume mount below to inspect the hugo output, IFF needed
      # - ./build:/output
    environment:
      - HUGO_THEME=academic
      - HUGO_WATCH=1
      # - HUGO_DESTINATION=/output
      - HUGO_REFRESH_TIME=60
      # - HUGO_BASEURL=john.muchovej.com
    ports: [ "5646:5646", ]
    command:
      - /run.sh  # from Dockerfile
      - --buildFuture
      - --disableFastRender
      - --verbose
      - --port=5646
      - --liveReloadPort=5646
